# docker-compose -f docker-compose.yml -fcompose.prod.yml up

version: '3.8'

services:
  app:
    container_name: my_go_app_prod 
    environment:
      - DB_DATABASE=DB_DATABASE_prod
      - DB_USER=DB_USER_prod
      - DB_PWD=DB_PWD_prod
      - DB_HOST=DB_HOST_prod
      - DB_PORT=DB_PORT_prod