# docker-compose -f docker-compose.yml -fcompose.prod.yml up


version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria_go 
    environment:
      - DB_USER=rootLibreri
      - DB_PWD=Comemierda
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_DATABASE=Libreria

  mongo:
    container_name: libreria_go_mongo
    environment:
      MONGO_INITDB_DATABASE: Libreria
      MONGO_INITDB_ROOT_USERNAME: rootLibreri
      MONGO_INITDB_ROOT_PASSWORD: Comemierda