# docker-compose -f docker-compose.yml -f compose.test.yml up libreri_do_test


version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: libreria_go_test 
    environment:
      - DB_USER=rootLibreria
      - DB_PWD=comemierda
      - DB_HOST=mongodb
      - DB_PORT=27017      
      - DB_DATABASE=Libreria_test
    networks:
      - network-mongodb

networks:
  network-mongodb:
    external: true




  # mongo:
  #   container_name: libreria_go_test_mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: rootLibreriaTest
  #     MONGO_INITDB_ROOT_PASSWORD: Comemierda
  #     MONGO_INITDB_DATABASE: Libreria_test