# docker-compose -f docker-compose.yml -f compose.dev.yml up


version: '3.8'

services:
  app:
    image: libreria_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: libreria_go_dev 
    environment:
      - DB_USER=rootLibreria
      - DB_PWD=comemierda
      - DB_HOST=mongodb
      - DB_PORT=27017      
      - DB_DATABASE=Libreria
    networks:
      - network-mongodb

networks:
  network-mongodb:
    external: true

  # mongo:
  #   container_name: libreria_go_dev_mongo
  #   environment:
  #     MONGO_INITDB_DATABASE: Libreria_dev
  #     MONGO_INITDB_ROOT_USERNAME: rootLibreriaDev
  #     MONGO_INITDB_ROOT_PASSWORD: Comemierda