# Dockerfile para pruebas

# Utiliza una imagen base de Go para pruebas
FROM golang:1.17-alpine



ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
    
# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de la aplicación al contenedor
COPY ./lib .

# Instala las dependencias y herramientas de pruebas, si es necesario
RUN apk add --no-cache git

# Ejecuta los comandos de pruebas
CMD ["go", "test", "./..."]


# docker build -t mi-app-test -f Dockerfile.test .
# docker run mi-app-test
